### ISSUE TITLE
Migrating Over From Threads to Channels

### ISSUE THREAD

**Issue by thegekka** [deltaxp0/dm-bot#4]
Both channels, threads, and forums have their advantages and disadvantages, but for what we are making, channels are much easier to do and have a better system for adding and kicking users.

- In threads, we need to make these threads to be private, and them making the bot pings the user, which can get messy if we have multiple threads because we D&D staffs ALSO needs to be in the private threads, which again, can be a hassle.
- In forums, there's no special permissions to hide post from members, which can lead people seeing what's going on in that specific sector, which can be problematic.

So Delta, **stop using threads and fucking switch over to channels.**

**Comment by thegekka** [comment]
@deltaxp0 stupid

**Comment by deltaxp0** [comment]
I don't see the point but sure.
