### ISSUE TITLE
Update !register Command

### ISSUE THREAD

**Issue by thegekka** [deltaxp0/dm-bot#7]
```
!register
```
User will put their discord username & ID (although this can be easily done, so no need of input), any preferred names, pronouns, and their DND experience. The bot will send a log of the person who uses the command to a channel with the information they inputted.

Permission is undetermined at the moment, so leave that blank, but still leave a place where we can input the permission later.

**Comment by deltaxp0** [comment]
Should be done. If you guys dislike something, let me know.
